### ISSUE TITLE
Allow specifying a relative WordPress version number

### ISSUE THREAD

**Issue by srtfisher** [alleyinteractive/action-test-php#4]
### Description

As a plugin maintainer I would like to be able to test against a rolling set of WordPress versions instead of just the `latest` OR maintaining the list ourself. For example, running this action with a matrix of versions where we specify `latest`, `latest-1`, `latest-2` where `latest-1` is the major release before the current latest (e.g., if 6.5 is `latest`, then 6.4 is `latest-1`, and so on).

### Use Case

When a developer wants to test a plugin they should be able to test against N number of versions of WordPress.

### Acceptance Criteria

- Allow a configuration option to specify a relative version of WordPress (e.g., `latest-1`), which would be `n` versions before the current one (so if 6.5 is latest, latest-1 = 6.4).
- Pull the list of versions from a WordPress.org API endpoint or feed so that they don't have to be manually maintained by us.

### Example DX

```yml
name: "All Pull Request Tests"

on:
  pull_request:
    branches:
      - production
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pr-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php-version: ['8.2', '8.1']
        wordpress-version: ['latest', 'latest-1', 'latest-2']
    concurrency:
      group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Run PHP Tests
        uses: alleyinteractive/action-test-php@develop
        with:
          php-version: ${{ matrix.php-version }}
          wordpress-version: ${{ matrix.wordpress-version }}
```
